# **MACHINE LEARNING LAB - 4 ( Backpropagation Algorithm )**

4. Build an Artificial Neural Network by implementing the Backpropagation algorithm and test the same using appropriate data sets.

In [3]:
import numpy as np

In [14]:
x = np.array([[0.66666667, 1.],
              [0.33333333, 0.55555556],
              [1., 0.66666667]])

y = np.array([[0.92],
              [0.86],
              [0.89]])

In [17]:
class Neural_Network:
    def __init__(self):

        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3


        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)

    def forward(self, X):

        self.z = np.dot(X, self.W1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        o = self.sigmoid(self.z3)
        return o

    def sigmoid(self, s):

        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):

        return s * (1 - s)

    def backward(self, X, y, o):

        self.o_error = y - o
        self.o_delta = self.o_error * self.sigmoidPrime(o)

        self.z2_error = self.o_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)

        self.W1 += X.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.o_delta)

    def train(self, X, y):

        o = self.forward(X)
        self.backward(X, y, o)

In [16]:
NN = Neural_Network()
for i in range(1000):
    print("\nInput: \n" + str(x))
    print("\nActual Output: \n" + str(y))
    print("\nPredicted Output: \n" + str(NN.forward(x)))
    print("\nLoss: \n" + str(np.mean(np.square(y - NN.forward(x)))))
    NN.train(x, y)


Streaming output truncated to the last 5000 lines.
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.91395522]
 [0.85963116]
 [0.89541393]]

Loss: 
2.1995331517897114e-05

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.91395629]
 [0.85963153]
 [0.89541245]]

Loss: 
2.19856264287546e-05

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.91395735]
 [0.8596319 ]
 [0.89541098]]

Loss: 
2.19759242801029e-05

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.91395842]
 [0.85963227]
 [0.8954095 ]]

Loss: 
2.196622507212337e-05

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

P